qa:
  stage: test
  image: yourlabs/python
  script: flake8

pytest:
  stage: test
  image: yourlabs/python
  script: py.test -v

pypi:
  stage: deploy
  only:
  - /^v\d+\./
  image: yourlabs/python:autoplay
  script:
  - autoplay run twine
